# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_tracks.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Change_Form(object):
    def setupUi(self, Change_Form):
        Change_Form.setObjectName("Change_Form")
        Change_Form.resize(312, 300)
        Change_Form.setStyleSheet("background-color: white;")
        self.verticalLayoutWidget = QtWidgets.QWidget(Change_Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setStyleSheet("display: inline-block;\n"
                                      "color: #33d9ff;\n"
                                      "font-weight: 700;\n"
                                      "text-decoration: none;\n"
                                      "user-select: none;\n"
                                      "padding: .5em 2em;\n"
                                      "outline: none;\n"
                                      "border: 2px solid;\n"
                                      "border-radius: 1px;\n"
                                      "transition: 0.2s;\n"
                                      "border-color: #33d9ff;")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addtrack_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addtrack_button.setObjectName("addtrack_button")
        self.addtrack_button.setStyleSheet("#addtrack_button {\n"
                                      "display: inline-block;\n"
                                      "color: #33d9ff;\n"
                                      "font-weight: 700;\n"
                                      "text-decoration: none;\n"
                                      "user-select: none;\n"
                                      "padding: .5em 2em;\n"
                                      "outline: none;\n"
                                      "border: 2px solid;\n"
                                      "border-radius: 1px;\n"
                                      "transition: all 0.3s;\n"
                                      "border-color: #33d9ff;\n"
                                      "}\n"
                                      "\n"
                                      "#addtrack_button:hover {\n"
                                      "    color: white;\n"
                                      "    background-color:#33d9ff;\n"
                                      "    cursor: pointer;\n"
                                      "}")
        self.horizontalLayout_5.addWidget(self.addtrack_button)
        self.close_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.close_button.setObjectName("close_button")
        self.close_button.setStyleSheet("#close_button {\n"
                                           "display: inline-block;\n"
                                           "color: #33d9ff;\n"
                                           "font-weight: 700;\n"
                                           "text-decoration: none;\n"
                                           "user-select: none;\n"
                                           "padding: .5em 2em;\n"
                                           "outline: none;\n"
                                           "border: 2px solid;\n"
                                           "border-radius: 1px;\n"
                                           "transition: all 0.3s;\n"
                                           "border-color: #33d9ff;\n"
                                           "}\n"
                                           "\n"
                                           "#close_button:hover {\n"
                                           "    color: white;\n"
                                           "    background-color:#33d9ff;\n"
                                           "    cursor: pointer;\n"
                                           "}")
        self.horizontalLayout_5.addWidget(self.close_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Change_Form)
        QtCore.QMetaObject.connectSlotsByName(Change_Form)

    def retranslateUi(self, Change_Form):
        _translate = QtCore.QCoreApplication.translate
        Change_Form.setWindowTitle(_translate("Change_Form", "Add tracks"))
        self.addtrack_button.setText(_translate("Change_Form", "+"))
        self.close_button.setText(_translate("Change_Form", "close"))
