# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(343, 450)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 321, 225))
        self.listWidget.setStyleSheet("display: inline-block;\n"
"color: #33d9ff;\n"
"font-weight: 700;\n"
"text-decoration: none;\n"
"user-select: none;\n"
"padding: .5em 2em;\n"
"outline: none;\n"
"border: 2px solid;\n"
"border-radius: 1px;\n"
"transition: 0.2s;\n"
"border-color: #33d9ff;")
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 240, 321, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.previos_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.previos_button.setStyleSheet("#previos_button {background-color: Transparent;\n"
"background-repeat:no-repeat;\n"
"border: none;\n"
"cursor:pointer;\n"
"overflow: hidden;  }      \n"
"\n"
"#previos_button:hover {background-color:  #33d9ff;}   \n"
"")
        self.previos_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Ресурс 5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previos_button.setIcon(icon)
        self.previos_button.setIconSize(QtCore.QSize(25, 25))
        self.previos_button.setObjectName("previos_button")
        self.horizontalLayout_5.addWidget(self.previos_button)
        self.pause_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pause_button.setStyleSheet("#pause_button{background-color: Transparent;\n"
"background-repeat:no-repeat;\n"
"border: none;\n"
"cursor:pointer;\n"
"overflow: hidden;  }      \n"
"\n"
"#pause_button:hover {background-color:  #33d9ff;}   ")
        self.pause_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/Ресурс 3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_button.setIcon(icon1)
        self.pause_button.setIconSize(QtCore.QSize(25, 25))
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout_5.addWidget(self.pause_button)
        self.play_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.play_button.setStyleSheet("#play_button{background-color: Transparent;\n"
"background-repeat:no-repeat;\n"
"border: none;\n"
"cursor:pointer;\n"
"overflow: hidden;  }      \n"
"\n"
"#play_button:hover {background-color:  #33d9ff;}   ")
        self.play_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/Ресурс 4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button.setIcon(icon2)
        self.play_button.setIconSize(QtCore.QSize(25, 25))
        self.play_button.setObjectName("play_button")
        self.horizontalLayout_5.addWidget(self.play_button)
        self.next_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.next_button.setStyleSheet("#next_button{background-color: Transparent;\n"
"background-repeat:no-repeat;\n"
"border: none;\n"
"cursor:pointer;\n"
"overflow: hidden;  }      \n"
"\n"
"#next_button:hover {background-color:  #33d9ff;}   ")
        self.next_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/Ресурс 6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_button.setIcon(icon3)
        self.next_button.setIconSize(QtCore.QSize(25, 25))
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_5.addWidget(self.next_button)
        self.repeat_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.repeat_button.setStyleSheet("#repeat_button{background-color: Transparent;\n"
"background-repeat:no-repeat;\n"
"border: none;\n"
"cursor:pointer;\n"
"overflow: hidden;  }      \n"
"\n"
"#repeat_button:hover {background-color:  #33d9ff;}   ")
        self.repeat_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/Ресурс 9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.repeat_button.setIcon(icon4)
        self.repeat_button.setIconSize(QtCore.QSize(25, 25))
        self.repeat_button.setObjectName("repeat_button")
        self.horizontalLayout_5.addWidget(self.repeat_button)
        self.valuemin_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.valuemin_button.setStyleSheet("#valuemin_button{background-color: Transparent;\n"
"background-repeat:no-repeat;\n"
"border: none;\n"
"cursor:pointer;\n"
"overflow: hidden;  }      \n"
"\n"
"#valuemin_button:hover {background-color:  #33d9ff;}   ")
        self.valuemin_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/Ресурс 8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.valuemin_button.setIcon(icon5)
        self.valuemin_button.setIconSize(QtCore.QSize(25, 25))
        self.valuemin_button.setObjectName("valuemin_button")
        self.horizontalLayout_5.addWidget(self.valuemin_button)
        self.valuemax_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.valuemax_button.setStyleSheet("#valuemax_button{background-color: Transparent;\n"
"background-repeat:no-repeat;\n"
"border: none;\n"
"cursor:pointer;\n"
"overflow: hidden;  }      \n"
"\n"
"#valuemax_button:hover {background-color:  #33d9ff;}   ")
        self.valuemax_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/Ресурс 7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.valuemax_button.setIcon(icon6)
        self.valuemax_button.setIconSize(QtCore.QSize(25, 25))
        self.valuemax_button.setObjectName("valuemax_button")
        self.horizontalLayout_5.addWidget(self.valuemax_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 310, 321, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.add_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.add_button.setStyleSheet("#add_button {\n"
"display: inline-block;\n"
"color: #33d9ff;\n"
"font-weight: 700;\n"
"text-decoration: none;\n"
"user-select: none;\n"
"padding: .5em 2em;\n"
"outline: none;\n"
"border: 2px solid;\n"
"border-radius: 1px;\n"
"transition: all 0.3s;\n"
"border-color: #33d9ff;\n"
"}\n"
"\n"
"#add_button:hover {\n"
"    color: white;\n"
"    background-color:#33d9ff;\n"
"    cursor: pointer;\n"
"}")
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_7.addWidget(self.add_button)
        self.dell_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.dell_button.setStyleSheet("#dell_button {\n"
"display: inline-block;\n"
"color: #33d9ff;\n"
"font-weight: 700;\n"
"text-decoration: none;\n"
"user-select: none;\n"
"padding: .5em 2em;\n"
"outline: none;\n"
"border: 2px solid;\n"
"border-radius: 1px;\n"
"transition: all 0.3s;\n"
"border-color: #33d9ff;\n"
"}\n"
"\n"
"#dell_button:hover {\n"
"    color: white;\n"
"    background-color:#33d9ff;\n"
"    cursor: pointer;\n"
"}")
        self.dell_button.setObjectName("dell_button")
        self.horizontalLayout_7.addWidget(self.dell_button)
        self.change_user_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_user_button.setGeometry(QtCore.QRect(10, 360, 321, 31))
        self.change_user_button.setStyleSheet("#change_user_button {\n"
"display: inline-block;\n"
"color: #33d9ff;\n"
"font-weight: 700;\n"
"text-decoration: none;\n"
"user-select: none;\n"
"padding: .5em 2em;\n"
"outline: none;\n"
"border: 2px solid;\n"
"border-radius: 1px;\n"
"transition: all 0.3s;\n"
"border-color: #33d9ff;\n"
"}\n"
"\n"
"#change_user_button:hover {\n"
"    color: white;\n"
"    background-color:#33d9ff;\n"
"    cursor: pointer;\n"
"}")
        self.change_user_button.setObjectName("change_user_button")
        self.renew_button = QtWidgets.QPushButton(self.centralwidget)
        self.renew_button.setGeometry(QtCore.QRect(10, 400, 321, 31))
        self.renew_button.setStyleSheet("#renew_button {\n"
                                              "display: inline-block;\n"
                                              "color: #33d9ff;\n"
                                              "font-weight: 700;\n"
                                              "text-decoration: none;\n"
                                              "user-select: none;\n"
                                              "padding: .5em 2em;\n"
                                              "outline: none;\n"
                                              "border: 2px solid;\n"
                                              "border-radius: 1px;\n"
                                              "transition: all 0.3s;\n"
                                              "border-color: #33d9ff;\n"
                                              "}\n"
                                              "\n"
                                              "#renew_button:hover {\n"
                                              "    color: white;\n"
                                              "    background-color:#33d9ff;\n"
                                              "    cursor: pointer;\n"
                                              "}")
        self.renew_button.setObjectName("renew_button")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 280, 311, 22))
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #33d9ff, stop:1 #33d9ff);\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 white, stop:1 white);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 18px;\n"
"    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"    border-radius: 3px;\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Player"))
        self.add_button.setText(_translate("MainWindow", "add"))
        self.dell_button.setText(_translate("MainWindow", "dell"))
        self.change_user_button.setText(_translate("MainWindow", "change user"))
        self.renew_button.setText(_translate("MainWindow", "refresh"))
